import { Applicant } from './applicant';

export const applicants: Applicant[] = [
    {
        firstName: 'firstName1',
        lastName: 'lastName1',
        email: 'email1@gmail.com',
        dob: '02/22/1234',
        address1: 'Earl, Heir to the Candy Kingdom Throne',
        address2: 'Earl, Heir to the Candy Kingdom Throne',
        country: 'United states',
        state: 'Missouri',
        city: 'Maryville',
        county: 'county2',
        phone: '1235467908',
        skills: 'skill1',
        lisence: 'lisence1',
        certification:'certification1',
        fileUpload:'pdf1',
        limitations:'deaf'
    
      },
      {
        firstName: 'firstName2',
        lastName: 'lastName2',
        email: 'email2@gmail.com',
        dob: '02/21/1233',
        address1: 'Earl, Heir to the Candy Kingdom ',
        address2: 'Earl, Heir to the Candy Kingdom Throne',
        country: 'United states',
        state: 'Missouri',
        city: 'Kansas',
        county: 'county3',
        phone: '1235467900',
        skills: 'skill2',
        lisence: 'lisence2',
        certification:'certification2',
        fileUpload:'pdf2',
        limitations:'dumb'
      },
      {
        firstName: 'firstName3',
        lastName: 'lastName3',
        email: 'email3@gmail.com',
        dob: '01/25/1236',
        address1: 'Earl, Heir to the Candy',
        address2: 'Earl, Heir to the Candy Kingdom Throne',
        country: 'United states',
        state: 'Missouri',
        city: 'Omaha',
        county: 'county3',
        phone: '1235464565',
        skills: 'skill3',
        lisence: 'lisence3',
        certification:'certification3',
        fileUpload:'pdf3',
        limitations:'deaff'
      },
      {
        firstName: 'firstName4',
        lastName: 'lastName4',
        email: 'email4@gmail.com',
        dob: '02/28/1234',
        address1: 'Earl, Heir',
        address2: 'Earl, Heir to the Candy',
        country: 'United states',
        state: 'Missouri',
        city: 'Maryville',
        county: 'county4',
        phone: '1233451234',
        skills: 'skill4',
        lisence: 'lisence4',
        certification:'certification4',
        fileUpload:'pdf4',
        limitations:'night blindness'
      },
]