// Assined to Sreevani

import { Applicant } from './applicant';

export const applicant: Applicant[] = [
    {
        firstName: 'Chandra Mouli',
        lastName: 'Kantipudi',
        email: 'chandra@gmail.com',
        dob: '02/22/1234',
        address1: 'Apt#123',
        address2: 'Horizon West Apts',
        country: 'United states',
        state: 'Missouri',
        city: 'Maryville',
        county: 'county2',
        phone: '1235467908',
        skills: 'Fire Safety',
        lisence: '1234566677',
        certification:'3453456789',
        fileUpload:'pdf1',
        limitations:'none'
    
      },
      {
        firstName: 'Hemanth',
        lastName: 'Narne',
        email: 'narne@gmail.com',
        dob: '02/21/1233',
        address1: 'Apt#12 ',
        address2: 'Horizon West Apts',
        country: 'United states',
        state: 'Missouri',
        city: 'Kansas',
        county: 'county3',
        phone: '1235467900',
        skills: 'Light Search',
        lisence: '1231234567',
        certification:'9879876788',
        fileUpload:'pdf2',
        limitations:'none'
      },
      {
        firstName: 'Kishan',
        lastName: 'Srinivas',
        email: 'kishan@gmail.com',
        dob: '01/25/1236',
        address1: 'Apt#235',
        address2: 'Horizon Wezt Apts',
        country: 'United states',
        state: 'Missouri',
        city: 'Maryville',
        county: 'county3',
        phone: '1235464565',
        skills: 'skill3',
        lisence: '6767676767',
        certification:'9898989898',
        fileUpload:'pdf3',
        limitations:'none'
      },
      {
        firstName: 'Sreevani',
        lastName: 'Anoohya',
        email: 'anoohya@gmail.com',
        dob: '02/28/1234',
        address1: 'Apt#63',
        address2: 'Horizon West Apts',
        country: 'United states',
        state: 'Missouri',
        city: 'Maryville',
        county: 'county4',
        phone: '1233451234',
        skills: 'light search',
        lisence: '9876543210',
        certification:'4564567809',
        fileUpload:'pdf4',
        limitations:'none'
      },
      {
        firstName: 'Vineeth',
        lastName: 'Agarwal',
        email: 'agarwal@gmail.com',
        dob: '02/28/1234',
        address1: 'Apt#43',
        address2: 'Horizon West Apts',
        country: 'United states',
        state: 'Missouri',
        city: 'Maryville',
        county: 'county4',
        phone: '1233451234',
        skills: 'Rescue',
        lisence: '9876543210',
        certification:'4564567809',
        fileUpload:'pdf4',
        limitations:'none'
      },
      
];